name: search
channels:
  - defaults
dependencies:
  - python=3.9
  - pandas
  - jupyterlab
  - pip:
      - elasticsearch==8.15.0
      - factory-boy==3.3.1
      - faker-vehicle==0.2.0
      - langchain-community==0.3.5
      - langchain-openai==0.2.6

      - streamlit==1.39.0
      - streamlit-antd-components==0.3.2
      - st-ant-tree==0.0.13
      - streamlit-searchbox==0.1.19